### PR TITLE
Check namespaces and class imports for leading backslash

### LINKED ISSUE #20: [CONTRIB-7828] Implement checks for namespace/import statements
Would be useful if the [guidelines regarding namespaces ](https://docs.moodle.org/dev/Coding_style#Namespaces)were enforced with Code checker, for example:

> Never use a leading backslash (\) in "namespace" and "use" statements.

---
Reporter: Paul Holden
Original issue: https://tracker.moodle.org/browse/CONTRIB-7828

### PR DESCRIPTION
**Pull request by andrewnicols**
Fixes #20

### CODE REVIEW

**Comment by stronk7** [comment]
Q: Shouldn't we also add `PSR12.Files.ImportStatement.LeadingSlash` to get imports also covered?

And little detail, it looks "strange" that our class is named "NoLeadingSlash", shouldn't it be better named "LeadingSlash". 

Similar sentiment with the problem name, we are naming it "NamespaceStartsWithSlash", that is redundant ("namespace") and uses different wording. Why not, also for the problem, just use "LeadingSlash".

FYC, ciao :-)

PS, I've seen that there are a few tests failing right now...

**Comment by andrewnicols** [comment]
> Q: Shouldn't we also add PSR12.Files.ImportStatement.LeadingSlash to get imports also covered?
Bah - I originally applied this to the extra ruleset which already has it. Updated to include it/.

> And little detail, it looks "strange" that our class is named "NoLeadingSlash", shouldn't it be better named "LeadingSlash".
> 
> Similar sentiment with the problem name, we are naming it "NamespaceStartsWithSlash", that is redundant ("namespace") and uses different wording. Why not, also for the problem, just use "LeadingSlash".

If I make this LeadingSlash and name the problem `LeadingSlash` it becomes `moodle.Namespace.LeadingSlash.LeadingSlash` which is also redundant.

Rather than that, I've tried to take inspiration from the PSR-12 one and now have:
`moodle.Namespace.NamespaceStatement.LeadingSlash`

I think the duplication of `Namespace` in both the Sniff type, and the sniff name is okay because it's a check of the Namespace statement and naming it simply `Statement` could be confusing - `moodle.Namespace.Statement` is fine, but `Statement` on its own may confuse.

Thoughts?

> PS, I've seen that there are a few tests failing right now...

phplint was actually picking this up already so I think I've got that now!

**Review by stronk7 — APPROVED** [review]
I like making it `NamespaceStatement` so we can add later more checks there.

Note: I'm completing the API checks for PHPUnit classes (that already have Namespace checks). Once working I plan to move them from being "phpunit only" to be "whole codebase" ones. Surely then we'll be adding more checks to the `NamespaceStatement` sniff added here.

**Comment by andrewnicols** [comment]
> Note: I'm completing the API checks for PHPUnit classes (that already have Namespace checks). Once working I plan to move them from being "phpunit only" to be "whole codebase" ones. Surely then we'll be adding more checks to the NamespaceStatement sniff added here.

Perfect - that was about what I had in mind too!

**Pull request merged**
