### PR TITLE
Add a new moodle-extra coding style

### PR DESCRIPTION
**Pull request by andrewnicols**
As dicussed in #45, and #25 it would be good to have a strict option.

This is an attempt largely based on the one I use daily (https://github.com/andrewnicols/moodle-cs-strict) with a few additions and removals.

### CODE REVIEW

**Comment by stronk7** [comment]
I like this, and we can go promoting things from the "extra" ruleset to the "normal" one while things evolve...

BTW, does "extra" sound ok for you? For some reason (not sure why, to be honest, maybe because of Spanish...) I'm not sure. Maybe "plus", "strict", "get_it_serious" (lol)...

In any case I'm not strong at all with the above, if you're happy with "extra", I'm happy too. Just tell and I will proceed.

Ciao :-)

**Comment by andrewnicols** [comment]
> BTW, does "extra" sound ok for you? For some reason (not sure why, to be honest, maybe because of Spanish...) I'm not sure. Maybe "plus", "strict", "get_it_serious" (lol)...

I went for `extra` because that's what WordPress do for theirs: https://github.com/WordPress/WordPress-Coding-Standards#standards-subsets

Their description is:
> extended ruleset with recommended best practices, not sufficiently covered in the WordPress core coding standards

I've also taken the liberty of updating the readme here to:
- describe both of the coding tsyles
- update information on how to use the new coding styles
- remove the old information on configuration (moodle-local_codecheck is now wrong, and the other options are far from ideal).

**Comment by stronk7** [comment]
Here we go! (note, I'll be making a release later today if that's ok for you)

**Comment by andrewnicols** [comment]
Works for me.

I considered adding some more rules but I feel we should add unit tests for what we have first.

I was also wondering about writing a sniff for data providers to make them statically defined.

**Review by stronk7 — APPROVED** [review]
Thanks @andrewnicols,

it looks great!

**Pull request merged**
