### PR TITLE
Add sniff to check for first line descriptions

### PR DESCRIPTION
**Pull request by andrewnicols**
Replaces:
* phpdocsfistline
* functiondescription

Replaces https://github.com/moodlehq/moodle-local_moodlecheck/pull/142

### CODE REVIEW

**Comment by stronk7** [comment]
Q: Does this cover cases like:

```
/**
 * This is the first line of the block.
 * But the second an following aren't separated enough and
 * make the block to look weird.
 */
<<files, classes, ..., but methods, that I think don't require it, go here >>
```

I mean, it sounds to me that the 1st line alone (with empty line after), has been always a requirement for them. But we haven't enforced it, I think. And this may be the perfect sniff for that.

**Comment by andrewnicols** [comment]
> Q: Does this cover cases like:
> 
> ```
> /**
>  * This is the first line of the block.
>  * But the second an following aren't separated enough and
>  * make the block to look weird.
>  */
> <<files, classes, ..., but methods, that I think don't require it, go here >>
> ```
> 
> I mean, it sounds to me that the 1st line alone (with empty line after), has been always a requirement for them. But we haven't enforced it, I think. And this may be the perfect sniff for that.

It doesn't cover that case right now, but it's not hard to add. Still, I'd prefer to do it as a separate PR in this case because there are a couple of ways to do it.

**Comment by stronk7** [comment]
> Still, I'd prefer to do it as a separate PR in this case because there are a couple of ways to do it.

Agreed, we can create a new issue with some thoughts about what we may need to check:
- Blank line between summary (short desc) and description (and for which elements).
- Blank like between descriptions and tags.
- Maybe some ordering and spacing between tag "groups" (copyright, author, license => params => return => other tags)
- ....
(I'd look to what the phpdoc proposal says for anything not explicitly defined in our guidelines)

I'll proceed to review this soon... ciao :-)

**Comment by stronk7** [comment]
Have created #136 to have the discussion above registered.

**Review by stronk7 — APPROVED** [review]

**Pull request merged**
