### PR TITLE
Add new sniff to detect and remove constructor @return docs

### PR DESCRIPTION
**Pull request by andrewnicols**

### CODE REVIEW

**Comment by andrewnicols** [comment]
@marinaglancy

Inspired by your docblock fixes.

**Comment by stronk7** [comment]
LGTM.

The removal looks a little bit complex, more yet, I must confess that I was sure that the fixer had some utility function to remove lines, but I was wrong and it only has functions to add new ones (`addNewline()` and `addNewlineBefore()).

**Comment by stronk7** [comment]
pong!

**Comment by andrewnicols** [comment]
I agree - there should really be a removeLine!! Drives me mad that there isn't.

@marinaglancy  are you able to review this?

**Comment by stronk7** [comment]
I've amended the commit to resolve the changelog conflicts.

**Review by stronk7 — APPROVED** [review]
This looks good enough for me, I've rebased it again and going to merge it now, towards a moodle-cs release in minutes... thanks!

**Pull request merged**
